language: go

go:
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x
- 1.x
- master

branches:
  only:
  - master
  - /^v.*$/

install:
- go get github.com/stretchr/testify/assert

script:
- go test -v -covermode=count -coverprofile=coverage.out

